#+OPTIONS: H:2 num:nil tags:nil timestamp:t
#+BEGIN_EXPORT html
---
title: My Rating System
tagline: What my rating number means
blog-category: watcher
category:
- watcher
---
#+END_EXPORT

* What Is A Rating System?

  In the context of watching stuff, *a rating system is a tool to
  subjectively measure and communicate the value of the media.* I want
  to stress *subjectively* because there is really no objective way of
  viewing anything without bias. One can grade things like in school
  with a number or a letter, one can rate things with a thumbs up or
  down, once can rank things with a place on a list, one can average a
  set of numbers, one can choose from many systems; ultimately, it
  should be a tool of communication whether it be subjective or not.
  (Honestly, there is no objective review but that's another post.)

  No rating system is flawless as well since it is based on one's
  current taste and preference. Where yesterday I liked it for visuals
  but hated it today because it is outdated, one's taste grows and
  matures over time so a constant reexamination is required and changed.
  One moment [[https://en.wikipedia.org/wiki/Pluto][Pluto]] was a planet, the next it is not; science is not
  exact and so am I. So if you think my rating of a video is wrong,
  remember it is just my take on it not yours which is ultimately
  matters at the end of the day.

  As a tool of communication, what I want to impart with my audience are
  simply three things:

  - Whether you should watch it or not
  - What I think it is from a viewing experience
  - What it means for me as a person

* My Rating System

  My rating simply is a scale of 1 to 5. Specifically, *one scale for the
  casual viewer, one scale for my taste, and a note on what it means to
  me* for a total of three scales of measure. I used to have a numeric scale of
  1 to 10 but I realize it did not help me understand what I was
  watching. Having only one numeric scale had the following problems:

  - I can't say which films are easy and hard to watch ::
       I give [[https://en.wikipedia.org/wiki/Angel%2527s_Egg][Angel's Egg]] and [[https://en.wikipedia.org/wiki/Song_of_the_Sea_%25282014_film%2529][Song of the Sea]] the highest rating I can
       give but the problem is that one film is very hard to watch from
       a recommendation point of view. I would also give the art films
       [[https://en.wikipedia.org/wiki/Enemy_(2013_film)][Enemy]] and [[https://en.wikipedia.org/wiki/Under_the_Skin_(2013_film)][Under The Skin]] the masterpiece rating but I can't
       recommend it to a casual viewer but I can't give it a lower
       rating just because it is hard to watch.
  - I can't separate my preference and bias ::
       As with the _Star Wars_ and _Studio Ghibli_ franchise, I might
       not be able to give a more objective point analysis since I am a
       fanboy to both. So having two scales allows me to consider the
       perspectives from which I am watching from.
  - I can't tell you what the rating really means for me ::
       If it is just a number or letter, how can I convey my feelings
       about the work in general? The film [[https://myanimelist.net/anime/32281/Kimi_no_Na_wa][Kimi no Na wa]] is masterfully
       done but I believe it is counter to everything done at that
       point, a number or tier cannot say that.

  Those are my primary problems that's why I switched over. The third of
  the scale is what this blog is for. My habit of watching films has led
  to create a watch list where I put a solitary rating of my second
  scale alone, so as an extension I will create a page indicating
  everything I reviewed and analyzed so far. For now my numeric or
  tiered scale of 1 to 5 can be described by the following description:

  - *5* ::
       A piece of art, should never be passed up
  - *4* ::
       A good work, deserves praise and your time
  - *3* ::
       A passable experience, good enough
  - *2* ::
       A bad work, a lot of errors
  - *1* ::
       Atrocious, a crime against humanity

  Not a mouthful, but that's pretty much how my scale works. I only
  recommend a 4 or 5, but I rarely watch a 3 and below since I do
  research on what good things I should watch and how I should watch it.
  The descriptions themselves are vague but I have several points from
  which I measure the overall quality:

  - *Visuals* ::
       Does the film look good? Important but not really drives my criteria
  - *Plot / Story* ::
       Does it tell a good story? Which is what a movie should do in the
       first place.
  - *Characters* ::
       Are the characters compelling? I still like [[https://en.wikipedia.org/wiki/Coraline_(film)][Coraline Jones]]
       despite being mean spirited.
  - *Cinematography* ::
       How is it filmed? I'm not an expert of but I can gauge a film's
       quality by the number of shots, cuts and edits which shows
       consideration, care and effort by the director
  - *Execution* ::
       Is well done? The primary criteria. Even if it is dumb and
       stupid, if it is well made; it is well made although I might not
       like it.
  - *Message / Theme* ::
       What is it saying? My secondary criteria. If it has a deeper
       meaning than a medium, then it becomes a far better work but
       execution is still king.

  Despite having multiple points, I don't put numbers on each one where
  others average over them as there total; my problem with that is one
  aspect could redeem the others despite being capped by a number. For
  example, [[https://en.wikipedia.org/wiki/Kingsglaive:_Final_Fantasy_XV][Kingsglaive]] is a 3 for me if not for the stellar animation
  but I really don't like it still. So how do I put a overall number on
  subjective scales? Enjoyment. Which is really a hard way to define
  itself. If the film is depressing like [[https://en.wikipedia.org/wiki/Melancholia_%25282011_film%2529][Melancholia]], are you suppose to
  rate the movie by fun or enjoyment or by the depressing or
  intellectual catharsis? It is very nuanced indeed for art or uncommon
  themes but most of the time I can gauge it based on the execution and
  cinematography then by its enjoyment, meaning and message and my
  reasons are written down for your judgment.

  My own guideline on what rating it is if it follows what that rating
  defines most of the time, I can argue about the pros and cons of the
  media but what helps me simplify it is in tiers although that too can
  be misplaced. I do want to stress my rating is not a review although
  you might consider that, I prefer to do analysis instead since there
  are so many of them. What I want others to tell me is how to watch the
  film or how I can appreciate it further, not why I shouldn't watch it.
  My first scale might be considered an watch approval, while the second
  scale is my personal approval and the third my deeper analysis. In
  short, I really like to think about them more than I want to watch
  them and that's what I want to impart if I can.

* As A Rater

  I am more an intellectual than enjoyment viewer. I may cry on [[https://en.wikipedia.org/wiki/Inside_Out_(2015_film)][Inside
  Out]] but I am more stimulated by what it entails; I may laugh on [[https://en.wikipedia.org/wiki/Scott_Pilgrim][Scott
  Pilgrim]] but I am observing the scene transitions, use of effects and
  respect on gamers; I have seen too many movies that I predict the
  story first before actually watching. I have been spoiled.

  I do have a secondary taste for animated or animation, such as
  cartoons and animes since they allow for greater variety in color,
  tone and setting. I like aesthetics more than graphics or maybe my
  eyes are bored with a normal shot of a town. So I am a fanboy of
  _Studio Ghibli_, _Cartoon Saloon_, _Makoto Shinkai_, _Satoshi Kon_ and
  so on. Color is such a nice thing.

  Lastly, I don't like passable material, something that is neither good
  nor bad. I constantly seek out and research approved and good
  material. I don't watch on-going series or media because I want the
  movie for what it is. Most of the time I go against the current media
  and watch oldies such as black and whites and older anime. My
  fundamental drive is that it must be good, and nothing is wasted more
  on a movie that just wastes your time. Popcorn movies are not my thing
  but I get a kick from time to time.

* At The End Of The Day

  It's just me explaining my feelings and thoughts on anything animated.
  My ratings are not absolute and I merely here to offer my perspective,
  not to rip apart your enjoyment but to simply respect your preference.
  Whatever that form might be, I should be able to reason out and not
  just say I feel like it. If I don't convey it properly, it is a
  failure on my part. But I might be just spinning my wheel if I don't
  analyze anything at all, so to test this out I will give my thoughts
  on [[https://myanimelist.net/anime/32281/Kimi_no_Na_wa][Kimi no Na wa]] for my next blog post.
