# Basic
name:               "Fn/Log"
title:              "Fn/Log"
description:        "* The diary of a mediocre developer *"

email:              "francisavmurillo@gmail.com"
github_username:    "FrancisMurillo"

bitcoin_address:    "38UKeSuwHb2f6GL1ahgAyJ58n6L2oWSXSx"
patreon_user_id:    "3312725"


# jekyll-seo-tag
url:                "//francismurillo.github.io"
author:             "Francis Murillo"
twitter:
  username:         "FVMurillo"

# URL
baseurl:            ""
permalink:          /:year-:month-:day-:title/ # required for org-export

# Markdown
markdown:           kramdown

# Var
major_mode:          Fundamental

# Navigation
nav: []

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate: 12
paginate_path: "/:num/"
