# Basic
name:               "Fn/Log"
title:              "Fn/Log"
description:        "The diary of a mediocre developer"

email:              "francisavmurillo@gmail.com"
github_username:    "FrancisMurillo"
twitter_username:   "FVMurillo"

# jekyll-seo-tag
url:                "//francismurillo.github.io"
author:             "Francis Murillo"
twitter:
  username:         "FVMurillo"

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag