# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fn/log
email: francisavmurillo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, I am Francis Murillo.
  If I were a robot, I would code for life.
  But I have a living shell, so I can only do so much.
  
  I don't know why you're here but if you want to here my thoughts, you're in the right place.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://francismurillo.com" # the base hostname & protocol for your site
twitter_username: FVMurillo
github_username:  FrancisMurillo

# Build settings
markdown: kramdown
